### ISSUE TITLE
step by step instructions for a simple checkout page

### ISSUE THREAD

**Issue by isthisthat** [flaviocopes/grav-plugin-shoppingcart-paypal#4]
Hello, are you planning to include some more detailed instructions on how to make a checkout form using this plugin? Thank you very much.

**Comment by flaviocopes** [comment]
As stated in https://github.com/flaviocopes/grav-plugin-shoppingcart-paypal/blob/develop/README.md, the plugin is an addon for the Shopping Cart plugin. 

Docs are listed in http://gravcart.com/docs

**Comment by isthisthat** [comment]
I was hoping for some more detail in the UI end since you say "This tutorial will guide you until you'll get a nice shop like this:" [Geek Toys] but that's never done. Thanks

**Comment by flaviocopes** [comment]
1. Install the Shopping Cart plugin
2. Make sure your site has a pages structure following this example http://gravcart.com/docs/pages-structure
3. Open your browser, and navigate to `/shop`

Using Antimatter will ensure the shop has some nice default styling, but any theme would work.
